routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'MaterialGroupController@index');

Route::resource('materialGroup', 'MaterialGroupController');

//Matterial routes
Route::get('/material/{materialGroup}', 'MaterialController@index')->name('material.index');
Route::delete('/material/{materialGroup}/{material}', 'MaterialController@destroy')->name('material.destroy');
Route::get('/material/{materialGroup}/create', 'MaterialController@create')->name('material.create');
Route::post('/material/{material}', 'MaterialController@store')->name('material.store');
Route::get('/material/{materialGroup}/{material}/edit', 'MaterialController@edit')->name('material.edit');
Route::patch('/material/{materialGroup}/{material}', 'MaterialController@update')->name('material.update');
//Route::resource('material', 'MaterialController');

app/Models/MaterialGroup.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class MaterialGroup extends Model
{
    /**
     * The table associated with the model.
     *
     * @var string
     */
    protected $table = 'material_groups';

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = ['name'];

    public function materials() {
        return $this->hasMany("App\Models\Material");
    }
}

app/Http/Controllers/MaterialGroupController.php
<?php

namespace App\Http\Controllers;

use App\Models\Material;
use App\Models\MaterialGroup;
use App\Repositories\MaterialGroupRepository;
use Illuminate\Http\Request;

class MaterialGroupController extends Controller
{
    /** @var MaterialGroupRepository */
    protected $materialGroup;

    private $valdiationRules = [
        'name' => 'required|max:255|unique:material_groups'
    ];

    /**
     * MaterialGroupController constructor.
     * @param MaterialGroup $materialGroup
     */
    public function __construct(MaterialGroup $materialGroup)
    {
        $this->materialGroup = new MaterialGroupRepository($materialGroup);
    }

    /**
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\View\View
     */
    public function index()
    {
        $materialGroups = $this->materialGroup->getAllWhichHaveMaterial();

        return view('materialGroups.list', compact('materialGroups'));
    }

    /**
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\View\View
     */
    public function create()
    {
        return view('materialGroups.create');
    }

    /**
     * @param int $materialGroupId
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\View\View
     */
    public function edit($materialGroupId)
    {
        $materialGroup = $this->materialGroup->show($materialGroupId);

        return view('materialGroups.create', compact('materialGroup'));
    }

    /**
     * @param Request $request
     * @return \Illuminate\Http\RedirectResponse
     * @throws \Illuminate\Validation\ValidationException
     */
    public function store(Request $request)
    {
        $this->validate($request, $this->valdiationRules);

        $this->materialGroup->create($request->only($this->materialGroup->getModel()->fillable));

        return redirect()->route('materialGroup.index')->with('success', 'New Material Group Was Added!');
    }

    /**
     * @param Request $request
     * @param $materialGroupId
     * @return \Illuminate\Http\RedirectResponse
     * @throws \Illuminate\Validation\ValidationException
     */
    public function update(Request $request, $materialGroupId)
    {
        $this->validate($request, $this->valdiationRules);

        $this->materialGroup->update($request->only($this->materialGroup->getModel()->fillable), $materialGroupId);

        return redirect()->route('materialGroup.index')->with('success', 'Material Group Was Updated!');
    }

    /**
     * @param int $materialGroupId
     * @return int
     */
    public function destroy($materialGroupId)
    {
        try {
            $this->materialGroup->delete($materialGroupId);
        } catch (\Exception $e) {
            return back()->with('error', 'Selected material group can not be deleted!');
        }

        return redirect()->route('materialGroup.index')->with('success', 'Material Group Was Deleted!');
    }
}

resources/views/materialGroups/create.blade.php
@extends('app')
@section('content')
	<div class="row">
		<div class="col-12 text-center mb-2">
			<h1>@if(isset($materialGroup))
					Edit
				@else
					Add New
				@endif
				Material Group</h1>
			@if($errors->has('name'))
				<div class="alert alert-danger mt-2 text-left">
					{{ $errors->first('name') }}
				</div>
			@endif
		</div>
		<div class="col-6">
			@if(isset($materialGroup))
				{!! Form::model($materialGroup, ['route' => ['materialGroup.update', $materialGroup->id], 'method' => 'patch']) !!}
			@else
				{!! Form::open(['route' => 'materialGroup.store']) !!}
			@endif
				<div class="form-group">
					<label for="name">Material Group</label>
					{!! Form::text('name',null,[
						'class' => 'form-control',
						'id' => 'name',
						'placeholder' => 'Material Group',
						'required'
					]) !!}
				</div>
			<div class="form-group">
				{!! Form::submit('Submit', [
					'class' => 'btn btn-outline-primary' ,
					'title' => 'Add',
				]) !!}
			{!! Form::close() !!}
			</div>
		</div>
	</div>
	@if(session('success'))
		<div class="alert alert-success">
			{{ session('success') }}
		</div>
	@endif
@endsection

resources/views/materialGroups/list.blade.php
@extends('app')
@section('content')
	@if(session('success'))
		<div class="alert alert-success">
			{{ session('success') }}
		</div>
	@endif
	@if(session('error'))
		<div class="alert alert-danger mt-2 text-left">
			{{ session('error') }}
		</div>
	@endif
	<div class="row">
		<div class="col-12">
			<a href="{{ route('material.create', ['materialGroup' => 0]) }}" class="btn btn-outline-secondary float-right  ml-2"> Add
				Material</a>
			<a href="{{ route('materialGroup.create') }}" class="btn btn-outline-primary float-right"> Add new Group</a>
		</div>
	</div>
	<div class="row">
		<div class="col-12 mb-2 text-center">
			<h1>Material Groups List</h1>
		</div>
		<div class="col-12">
			<table class="table table-striped">
				<thead class="thead-dark">
				<tr>
					<th scope="col" style="width: 1%" class="text-center">#</th>
					<th scope="col" style="width: 70%" class="text-left">Group Name</th>
					<th scope="col" class="text-right">Actions</th>
				</tr>
				</thead>
				<tbody>
					@foreach($materialGroups as $materialGroup)
						<tr>
							<td scope="row" class="text-center">{{ $materialGroup->id }}</td>
							<td class="text-left">{{ $materialGroup->name }}</td>
							<td class="text-right">
								{!! Form::open(['route' => ['materialGroup.destroy', $materialGroup->id], 'method' => 'delete']) !!}
									<div class='btn-group'>
										<a href="{!! route('material.index', ['materialGroup' => $materialGroup->id]) !!}" class='btn btn-outline-secondary mr-2'>Materials</a>
										<a href="{!! route('materialGroup.edit', [$materialGroup->id]) !!}" class='btn btn-outline-primary mr-2'>Edit</a>
										{!! Form::button('Delete', [
											'type' => 'submit',
											'class' => 'btn btn-outline-danger',
											'onclick' => "return confirm('Delete Material Group?')"
										]) !!}
									</div>
								{!! Form::close() !!}
							</td>
						</tr>
					@endforeach
				</tbody>
			</table>
			{{ $materialGroups->links() }}
		</div>
	</div>
@endsection